# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a38684b0e42f48401689d0d0bbf7f6950c8e08825deb67343c14e128a1e5f7ae054ab3baa9ab8ccb5c3118637a5e6d9776fffd2be8f2e9b7f902988b2d42494

test:
  secret_key_base: 8aebaeeec1f63007e7abfb1bc08652ca6cf695ff610462596896d78bc6f5fb7db19a4b20c9671623f030dc551957e7b7c325c8a348008b740ca5495718aced9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
